### ISSUE TITLE
Anatomical entities showing up as a child of its own term

### ISSUE THREAD

**Issue by laurajackson** [phenoscape/phenoscape-kb-ui#43] opened 2015-06-16 17:18 UTC
When I search a term in the KB (i.e., pectoral fin), I get pectoral fin as a child term of itself. Both terms ('pectoral fin' as parent and child) have different IDs, the parent term has UBERON:0000151, and the child 'pectoral fin' term has obo:ZFA_0001161 as the ID.

This seems to be the case for all terms I have tried in the KB.

**Comment by balhoff** [comment] 2015-06-22 19:30
This is a duplicate of #38.

**Closed as completed by balhoff** 2015-06-22 19:30 UTC
Labels: duplicate
