### ISSUE TITLE
The classification view doesn't show which descendants have phenotypes

### ISSUE THREAD

**Issue by prashanti** [phenoscape/phenoscape-kb-ui#62] opened 2015-07-07 00:01 UTC
For example, only two of the four descendants of Leporellus have phenotypes associated with them. This is not apparent from http://kb.phenoscape.org/#/taxon/http://purl.obolibrary.org/obo/VTO_0038632?tab=classification

**Comment by balhoff** [comment] 2016-01-05 19:47
This is a duplicate of #54.

**Closed as completed by balhoff** 2016-01-05 19:47 UTC
Labels: duplicate
